#!/usr/bin/env python
import rospy, math, random
import numpy as np
from std_msgs.msg import Float32
from sensor_msgs.msg import PointCloud2
from laser_geometry import LaserProjection
from roslib import message
from sensor_msgs import point_cloud2 
def points():
    data='msg.data'
    x1=[]
    y1=[]
    z1=[]
    for p in point_cloud2.read_points(data,skip_nans=True,field_names=("x","y","z")):
        x1=x1.append(p[0])
        y1=y1.append(p[1])
        z1=z1.appebd(p[2])
        print("x: %f y: %f z: %f",p[0],p[1],p[2])
    pub1.publish(x1)
    pub2.publish(y1)
    pub3.publish(z1)

if __name__=='__main__':
    rospy.init_node('points')
    
    sub=rospy.Subscriber('Sensor/points', Float32, points)
    
    try:
        points()
    except rospy.ROSInterruptException:
        pass
    
    rospy.spin()
